name: legos
on:
  push:
    branches: development
jobs:
  fw:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: CMake Setup
        run: cmake -G Ninja -B build
      - name: CMake Build
        run: cmake --build build --target all
      - name: CTest
        run: ctest --test-dir build --parallel
    container:
      image: ghcr.io/nupole/hdl-tools:development